### ISSUE TITLE
Benefit of this package vs RainLab.User plugin

### ISSUE THREAD

**Issue by scottbedard** [Teranode/october-laravel-auth-bridge#1]
Hi, this might be a silly question, but what is the benefit of using this technique for authentication vs using the [RainLab.User](https://github.com/rainlab/user-plugin) repository? Is one approach better than the other for certain use cases?

Thanks in advance!

**Comment by Denoder** [comment]
@scottbedard 

Not a silly question at all. I asked myself the same thing when I was making it. The first issue was coming across was that I "wanted" to use luketower's october-passport plugin (or just the plain passport package), but the current state of the October Library doesn't allow for passport to work correctly (the laravel-auth branch doesnt work either) because passport uses the auth guard contract which a part of laravel's auth and auth manager, so by extension I "have" to use laravel's auth core container

See: https://github.com/Teranode/october-laravel-auth-bridge/blob/master/src/Foundation/Application.php#L75

I thought it would be difficult to integrate but its just the opposite, if they had just add that container, and just "extended from the core auth container they could just have their own auth guard with their own overridden functions for october for managing logins and authentication while still having laravel's auth.

see https://github.com/Teranode/october-laravel-auth-bridge/blob/master/src/Auth/AuthServiceProvider.php#L36

and https://github.com/Teranode/october-laravel-auth-bridge/blob/master/src/Auth/AuthManager.php

That's why you see you have to change the Foundation Application and the kernel. I wanted to do this from a simple plugin, but the Auth service provider is needed before passport, but passport gets loaded in before auth due to it's composer.

-----

once you've installed this and want to use it with rainlab.user its not difficult either, you just have to change a small few things in the plugin's auth manager and the Plugin.php in terms of extending this package and using traits.

**Comment by scottbedard** [comment]
Very cool, thanks for the info!
